cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    th:
      email: 1345412477@qq.com
      failed_login_attempts: 0
      logged_in: false
      name: Tang Heng
      password: qqq
    wt:
      email: 2726234495@qq.com
      failed_login_attempts: 0
      logged_in: false
      name: Wu Tao
      password: qqq
      email: 980259394@qq.com
      failed_login_attempts: 0
      logged_in: false
      name: Wu Yuhao
      password: qqq
pre-authorized:
  emails:
  - melsby@gmail.com